- hosts: localhost
  gather_facts: false

  vars_files:
    - vars.yml

  tasks:
    - name: Install python dependencies
      pip:
        name: "{{ item }}"
      loop: "{{ packages }}"

    - name: Log into DockerHub
      community.docker.docker_login:
        username: "{{ dockerhub_username }}"
        password: "{{ lookup('env','DOCKERHUB_TOKEN') }}"

    - name: Build image
      community.docker.docker_image:
        build:
          path: "{{ dockerfile_path }}"
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        push: true
        source: build
