- hosts: localhost
  gather_facts: false

  vars_files:
    - vars.yml

  tasks:
    - name: Install python dependencies
      pip:
        name: "{{ item }}"
      loop: "{{ packages }}"

    - name: "Check running containers named: {{ container_name }}"
      shell: docker ps | grep "{{ container_name }}"
      ignore_errors: true
      register: result

    - name: Stop and remove existing container
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent
      when: result.rc == 0

    - name: Start new build container
      command: docker run -dt -v "$PWD/..:/tmp/vimwiki" --name "{{ container_name }}" "{{ image_name }}:{{ image_tag }}"

    - name: Copy vimwiki notes to vimwiki container directory
      community.docker.docker_container_exec:
        container: "{{ container_name }}"
        command: /bin/sh -c "cp -r vimwiki /root/"
        chdir: "/tmp/vimwiki"

    - name: Generate html files
      community.docker.docker_container_exec:
        container: "{{ container_name }}"
        command: /bin/sh -c "vim +VimwikiAll2HTML +q index.md && cp -r site_html /tmp/vimwiki/"
        chdir: "{{ container_vimwiki }}"

    - name: Stop and remove container
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent
