- hosts: localhost
  gather_facts: false

  vars_files:
    - vars.yml

  tasks:
    - name: Install python dependencies
      pip:
        name: "{{ item }}"
      loop: "{{ pip_packages }}"

    - name: Start new build container; Generate HTML files
      docker_container:
        name: "{{ container_name }}"
        state: started
        image: "{{ image_name }}:{{ image_tag }}"
        cleanup: true
        detach: false
        volumes:
          - "{{ host_vimwiki_path }}:/root/vimwiki"
