- hosts: localhost
  gather_facts: false

  vars_files:
    - vars.yml

  tasks:
    - name: Install python dependencies
      pip:
        name: "{{ item }}"
      loop: "{{ pip_packages }}"

    - name: Install dependencies
      yum:
        state: present
        name: "{{ item }}"
      loop:
        - rsync
      become: true

    - name: Create directory "{{ httpd_path }}"
      file:
        path: "{{ httpd_path }}"
        state: directory
        mode: '0755'
      become: true

    - name: Synchronization html files to httpd location
      synchronize:
        src: '{{ host_artifacts_path }}'
        dest: "{{ httpd_path }}"
      become: true

    - name: Setup httpd container
      docker_container:
        name: "{{ web_container_name }}"
        state: started
        restart_policy: always
        image: "{{ webserver_image }}"
        ports:
          - "{{ host_port }}:80/tcp"
        volumes:
          - "{{ httpd_path }}:{{ httpd_container_path }}"
