- hosts: localhost
  gather_facts: false

  vars:
    - httpd_path: '/var/www/html'
    - httpd_container_path: '/usr/local/apache2/htdocs'
    - container_name: 'vimwiki-webserver'
    - host_port: '8080'

  tasks:
    - name: Install python dependencies
      pip:
        name: "{{ item }}"
      loop:
        - requests
        - docker

    - name: Install dependencies
      yum:
        state: present
        name: "{{ item }}"
      loop:
        - rsync
      become: true

    - name: Create directory "{{ httpd_path }}"
      file:
        path: "{{ httpd_path }}"
        state: directory
        mode: '0755'
      become: true

    - name: Synchronization html files
      synchronize:
        src: '../html/'
        dest: "{{ httpd_path }}"
      become: true

    - name: Setup httpd container
      docker_container:
        name: "{{ container_name }}"
        state: present
        restart_policy: always
        image: httpd:alpine3.15
        ports:
          - "{{ host_port }}:80/tcp"
        volumes:
          - "{{ httpd_path }}:{{ httpd_container_path }}"
