name: Pipeline

on:
  workflow_dispatch:

jobs:
  Container:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Install ansible and collections
        run: |
          sudo apt -y install ansible python3
          ansible-galaxy collection install -r requirements.yml

      - name: Build and push container image
        run: ansible-playbook ./playbooks/build-image.yml -c local
        env:
          ANSIBLE_FORCE_COLOR: '1'
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  Build:
    needs: Container
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Clone notes repo
        uses: actions/checkout@v2
        with:
          path: 'vimwiki'
          ref: 'master'
          repository: 'LexVar/notes'
          ssh-key: ${{ secrets.REPO_NOTES_KEY }}

      - name: Install ansible and collections
        run: |
          sudo apt -y install ansible python3
          ansible-galaxy collection install -r requirements.yml

      - name: Buid html files in docker container
        run: ansible-playbook ./playbooks/build.yml -c local
        env:
          ANSIBLE_FORCE_COLOR: '1'

      - uses: actions/upload-artifact@v2
        with:
          name: vimwiki-html
          path: vimwiki/site_html/*

  Deploy:
    needs: Build
    runs-on: [self-hosted, linux, arm64, raspi]

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: vimwiki-html
          path: 'html'

      - name: Install ansible and collections
        run: |
          sudo dnf -y install epel-release
          sudo dnf -y install ansible python3
          ansible-galaxy collection install -r requirements.yml

      - name: Deploy website
        run: ansible-playbook ./playbooks/deploy.yml -c local
        env:
          ANSIBLE_FORCE_COLOR: '1'
