name: Pipeline

on:
  workflow_dispatch:

jobs:
  Container:
    runs-on: self-hosted

    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          path: 'repo'

      - name: Build container
        run: docker build -t docker.io/lexvar/vimwiki-build:latest repo/

      # - name: Login to dockerhub
      #   run: docker login -u lexvar -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} docker.io
      # - name: Push container to dockerhub
      #   run: docker build -t vimwiki-build:latest repo/

  Build:
    needs: Container
    runs-on: self-hosted

    container:
      image: docker.io/lexvar/vimwiki-build:latest

    steps:
      - name: Clone notes repo
        uses: actions/checkout@v2
        with:
          path: '/root/vimwiki'
          ref: 'master'
          repository: 'LexVar/notes'
          ssh-key: ${{ secrets.REPO_PRIVATE_KEY }}

      - name: Generate html from markdown
        run: |
          cd /root/vimwiki
          vim +VimwikiAll2HTML +q index.md

      - uses: actions/upload-artifact@v2
        with:
          name: vimwiki-html
          path: /root/vimwiki/site_html/*

  Deploy:
    needs: Build
    runs-on: self-hosted

    steps:
      - name: Make dir '/var/www/html'
        run: sudo mkdir -p /var/www/html/

      - uses: actions/download-artifact@v2
        with:
          name: vimwiki-html
          path: '/var/www/html'
        
      - name: Setup apache
        run: |
          sudo dnf install -y httpd
          sudo sed -i "s:Listen 80:Listen 8080:" /etc/httpd/conf/httpd.conf
          sudo systemctl enable httpd
          sudo systemctl restart httpd
