name: Pipeline

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: tmp
      
      - name: Convert markdown to HTML
        uses: lifepal/markdown-to-html@v1.2
        with:
          text: $GITHUB_WORKSPACE/tmp/index.md
          html: $GITHUB_WORKSPACE/index.html
        
  deploy:
    runs-on: self-hosted

    steps:
      - name: Make dir '/var/www/html'
        run: sudo mkdir -p /var/www/html/
      
      - name: Copy to '/var/www/html'
        run: sudo cp $GITHUB_WORKSPACE/*.html /var/www/html/
        
      - name: Start nginx
        run: sudo systemctl start nginx
