name: Pipeline

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Install vimwiki markdown dependencies
        run: |
          sudo mkdir -p /home/avalente/.vim/pack/plugins/start
          sudo dnf install python3 vim git -y
          pip3 install --user vimwiki_markdown

      - name: Clone repo
        uses: actions/checkout@v2
        with:
          path: 'tmp'

      - name: Install vimwiki
        run: stat ~/.vim/pack/plugins/start/vimwiki || git clone https://github.com/vimwiki/vimwiki.git ~/.vim/pack/plugins/start/vimwiki

      - name: Generate markdown profiles
        run: |
          cp $GITHUB_WORKSPACE/tmp/.vimrc /home/avalente/

      - name: Generate html
        run: |
          sed -i "s:\$VIMWIKI:$GITHUB_WORKSPACE/tmp:" $GITHUB_WORKSPACE/tmp/.vimrc
          cd $GITHUB_WORKSPACE/tmp && vim +VimwikiAll2HTML +q index.md

  deploy:
    # Dependency, needs build before deploy
    needs: build
    runs-on: self-hosted

    steps:
      - name: Make dir '/var/www/html'
        run: sudo mkdir -p /var/www/html/
      
      - name: Copy to '/var/www/html'
        run: |
          sudo rm -r /var/www/html/*
          sudo cp -r $GITHUB_WORKSPACE/tmp/site_html/* /var/www/html/
        
      - name: Setup apache
        run: |
          sudo dnf install -y httpd
          sudo sed -i "s:Listen 80:Listen 81:" /etc/httpd/conf/httpd.conf
          sudo systemctl enable httpd
          sudo systemctl restart httpd
