name: Pipeline

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Log markdown files
        run: ls -l
        working-directory: ./vimwiki_deploy
      
      - name: Markdown to HTML
        env:
          text: ./vimwiki_deploy/index.md
          html: index.html
        uses: lifepal/markdown-to-html@v1.2
        
  deploy:
    runs-on: self-hosted

    steps:
      - name: Copy to '/var/www/html'
        run: cp *.html /var/www/html/
        
      - name: Start nginx
        run: systemctl start nginx
